#ifndef QUIKMULTIBRIDGE_GLOBAL_H
#define QUIKMULTIBRIDGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QUIKMULTIBRIDGE_LIBRARY)
#  define QUIKMULTIBRIDGE_EXPORT Q_DECL_EXPORT
#else
#  define QUIKMULTIBRIDGE_EXPORT Q_DECL_IMPORT
#endif

#endif // QUIKMULTIBRIDGE_GLOBAL_H
